name: MobCapManager
version: 1.0.0
main: tech.sebazcrc.mobcap.MobCapPlugin
api-version: 1.15
authors: [SebazCRC]
description: Sistema avanzado de gesti칩n de MobCap basado en Permadeath
website: https://github.com/SebazCRC

commands:
  mobcap:
    description: Comando principal para gestionar MobCap
    usage: /mobcap <info|set|double|reset|reload>
    permission: mobcap.use
    aliases: [mc]
  mobcapinfo:
    description: Muestra informaci칩n detallada del MobCap
    usage: /mobcapinfo
    permission: mobcap.use
    aliases: [mcinfo]

permissions:
  mobcap.use:
    description: Permite usar comandos b치sicos de MobCap
    default: true
  mobcap.admin:
    description: Permite administrar la configuraci칩n de MobCap
    default: op
    children:
      mobcap.use: true