name: MobCapManager
version: 2.0.0
main: tech.sebazcrc.mobcap.MobCapPlugin
api-version: 1.15
authors: [SebazCRC]
description: Sistema avanzado de gestión de MobCap con spawn personalizado y optimización automática
website: https://github.com/SebazCRC
softdepend: [Permadeath]

commands:
  mobcap:
    description: Comando principal para gestionar MobCap
    usage: /mobcap <info|setbase|doble|triple|normal|habilitar|deshabilitar|reset|reload|mob>
    permission: mobcap.use
    aliases: [mc, mobcapmanager]
  mobcapinfo:
    description: Muestra información detallada del MobCap
    usage: /mobcapinfo
    permission: mobcap.use
    aliases: [mcinfo, mobcapstatus]

permissions:
  mobcap.use:
    description: Permite usar comandos básicos de MobCap
    default: true
  mobcap.admin:
    description: Permite administrar la configuración de MobCap
    default: op
    children:
      mobcap.use: true